GET http://localhost:3000/
Content-Type: application/json
###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "ya@yahoo.com",
    "name": "omer",
    "password": "Rc123456!"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "ya@yahoo.com",
    "password": "Rc123456!"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "admin@email.com",
    "password": "Rc123456!"
}
###
GET http://localhost:3000/api/v1/information
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlhQHlhaG9vLmNvbSIsIm5hbWUiOiJvbWVyIiwicGFzc3dvcmQiOiIkMmIkMTAkeE5tLkVtS1Z1clVzdDdYdVJtcjh4T0ZWaGZJVkxCQlpyT1o1a1Bkd1dubzNwNnFtOUVraGUiLCJpYXQiOjE2MzgyOTI2ODJ9.C6rKJ33nQX9IjyNJ4Hxck7z99IvsckHj2J1waFOqd30"

###
POST http://localhost:3000/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlhQHlhaG9vLmNvbSIsIm5hbWUiOiJvbWVyIiwicGFzc3dvcmQiOiIkMmIkMTAkeE5tLkVtS1Z1clVzdDdYdVJtcjh4T0ZWaGZJVkxCQlpyT1o1a1Bkd1dubzNwNnFtOUVraGUiLCJpYXQiOjE2MzgyOTI2NjN9.gua99A22pjUjFiwiDGsXHkOKDRFGqnxwgfaK6hbYMa0"
}
###
GET  http://localhost:3000/api/v1/users
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsIm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJFh5Wk9aSUJDM0pjUVUzMDZad1g3b3VlNnh1NjJUcUx5bDF6MGxrMUxZWWFtaWtMLnZCbkxtIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjM4Mjk0MTAwfQ.q_-nMRI97qYlV31oE2WVBbBa5880-fu34mFXRdwhMmg" 