OPTIONS  http://localhost:3000/
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsIm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJFh5Wk9aSUJDM0pjUVUzMDZad1g3b3VlNnh1NjJUcUx5bDF6MGxrMUxZWWFtaWtMLnZCbkxtIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjM4Mjk2NDYyfQ.vW9Aflz03YmHNm8PEB1aY3dQ0SWTWi4mDRHsJsXmsAQ"
###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "ya@yahoo.com",
    "name": "omer",
    "password": "Rc123456!"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "ya@yahoo.com",
    "password": "Rc123456!"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "admin@email.com",
    "password": "Rc123456!"
}
###
GET http://localhost:3000/api/v1/information
Content-Type: application/json
Authorization: "Bearer 9IjyNJ4Hxck7z99IvsckHj2J1waFOqd30"

###
POST http://localhost:3000/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsIm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJFh5Wk9aSUJDM0pjUVUzMDZad1g3b3VlNnh1NjJUcUx5bDF6MGxrMUxZWWFtaWtMLnZCbkxtIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjM4Mjk1MzI2fQ.9bOjYSj_V07WMaUebywTsy-0d0YUYu8Za5QtsZaySic"
}
###
GET  http://localhost:3000/api/v1/users
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsIm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJFh5Wk9aSUJDM0pjUVUzMDZad1g3b3VlNnh1NjJUcUx5bDF6MGxrMUxZWWFtaWtMLnZCbkxtIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjM4Mjk1MzI2fQ.9bOjYSj_V07WMaUebywTsy-0d0YUYu8Za5QtsZaySic" 